%% START
%{
    Name: Soumitra Mehrotra , Shreyas Hervatte, Vikram Poddar, Umar Farooq
    Computer Vision II - Project 2 implementation
    Description: The script file which uses the coordinates generated by
    the translation into 3D.
    *** Loads each of the input image in loop
    *** Calculated the A and[R t] parameter matrices of that image using
    the camera parameters function.
    *** COnverts the 3D cordinates of object placed to 2D u,v coordinated.
    *** COnverts the 3D coordinates of the feature points to 2D.
    *** plots the points onto  the loaded image 
               i.e the feature points & the object.

    NOTE::: To  skip the feature points to be plotted comment out the line
        plot(coludtrans(:,1),coludtrans(:,2),'+r')
   
%}
%% CODE
% Looping on all  the images in dataset
for j = 1:16
    
framename = "frame" + j + ".jpg";

% Caluclationg the camera parameters for each image
[A, R_t] = camera_parameters(framename);

% initializing output matrix
yy = zeros(length(TranslatedObject),1) + 1;
TranslatedObject_new = [TranslatedObject yy];

ObjectIn2D = zeros(length(TranslatedObject),3);

%Looping on for every coordinate point and using formula below finding the
 % 2D translated coordinated in u,v plane

for i = 1:length(TranslatedObject)
    ObjectIn2D(i,:) = A*R_t*TranslatedObject_new(i,:)';
    ObjectIn2D(i,1) =  ObjectIn2D(i,1)/ ObjectIn2D(i,3);
    ObjectIn2D(i,2) =  ObjectIn2D(i,2)/ ObjectIn2D(i,3);
end

%Looping on for every coordinate point and using formula below finding the
 % 2D translated coordinated in u,v plane
 
yy = zeros(length(p_best),1) + 1;
coludpoints = [p_best yy];

coludtrans = zeros(length(p_best),3);

for i = 1:length(p_best)
    coludtrans(i,:) = A*R_t*coludpoints(i,:)';
    coludtrans(i,1) =  coludtrans(i,1)/ coludtrans(i,3);
    coludtrans(i,2) =  coludtrans(i,2)/ coludtrans(i,3);
end
% FIle location used for projecting the object for  the points

coludtrans = coludtrans(:,1:2);
txt = "C:\Users\umarf\Downloads\Computer Vision\Project 2\final\extract_frames\frames\" + framename;

I = imread(txt);


ObjectIn2D = ObjectIn2D(:,1:2);
figure(1)
imshow(I)
hold on
%% Comment below line to skip the printing of feature coordinated onto image
plot(coludtrans(:,1),coludtrans(:,2),'+r')
 
%% Plotting all the 6 sides of object beinng placed in 2D plane converted onto the image

poly_2d(ObjectIn2D(1,:),ObjectIn2D(2,:),ObjectIn2D(3,:),ObjectIn2D(4,:),'r')
poly_2d(ObjectIn2D(5,:),ObjectIn2D(6,:),ObjectIn2D(7,:),ObjectIn2D(8,:),'r')
poly_2d(ObjectIn2D(2,:),ObjectIn2D(3,:),ObjectIn2D(7,:),ObjectIn2D(6,:),'c')
poly_2d(ObjectIn2D(3,:),ObjectIn2D(4,:),ObjectIn2D(8,:),ObjectIn2D(7,:),'k')
poly_2d(ObjectIn2D(1,:),ObjectIn2D(2,:),ObjectIn2D(6,:),ObjectIn2D(5,:),'k')
poly_2d(ObjectIn2D(1,:),ObjectIn2D(2,:),ObjectIn2D(3,:),ObjectIn2D(4,:),'r')
poly_2d(ObjectIn2D(4,:),ObjectIn2D(1,:),ObjectIn2D(5,:),ObjectIn2D(8,:),'c')

%% Saving the image with the frame name
saveas(1,framename)
end